name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    # There are a default set of these enabled - you may need to add closed if you want to run a workflow
    # on merge.
    types:
      - closed
      - opened
      - synchronize
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        # Input has to be provided for the workflow to run
        required: false
  # schedule:
  # Daily at 8:20 UTC
  # cron: '20 8 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    outputs:
      output1: ${{ steps.output1.outputs.test }}

    steps:
      # Check out the code to begin with
      - uses: actions/checkout@v2

      # Take the node JS version from the matrix and set it up
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          # Here is an example of using context in an expression
          node-version: ${{ matrix.node-version }}
          # Cache the packages to speed up runs
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      # Run yarn CI
      - run: yarn ci

      # Run jest tests
      - name: Running jest tests
        run: yarn test

      - name: Create a warning annotation
        run: |
          echo "WARN: This is a warning"
      - name: Create an error annotation
        run: |
          echo "ERROR: This is an error"
      - name: Set an output for other jobs
        id: output1
        run: echo "::set-output name=test::hello"

      - name: Publish package
        # Run this step just for releases
        if: github.event.release
        run: yarn publish
        env:
          # The GITHUB_TOKEN is automatically generated for each workflow run
          # it is scoped to access in the same repo - you can also use a PAT here if needed
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  other-thing:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: |
          echo "A post publish step gets the output: ${{ needs.build.output1 }}"

  post-publish:
    runs-on: ubuntu-latest
    needs: [other-thing]
    steps:
      - run: |
          echo "A post publish step"

  greet:
    runs-on: ubuntu-latest
    if: github.event.workflow_dispatch
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
